# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a1=np.random.random((3,3,3))
a1

array([[[0.51142345, 0.14474948, 0.68947873],
        [0.48590139, 0.59079487, 0.39684943],
        [0.56965038, 0.92020438, 0.01895174]],

       [[0.45469846, 0.63870097, 0.71937989],
        [0.94109997, 0.44550554, 0.01801689],
        [0.40056516, 0.24818201, 0.8135077 ]],

       [[0.24771963, 0.53418199, 0.02664544],
        [0.14681501, 0.49697843, 0.16677582],
        [0.41537014, 0.98868962, 0.90851585]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [20]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
a3=np.array([0,0,0])
a4=a2
np.fill_diagonal(a4[:-1,1:],a3)
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


NameError: name 'lower' is not defined

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [31]:
a1=np.zeros((8,8))
a1[::2,::2]=1
a1[1::2,1::2]=1
a1

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 4. Normalize a 5x5 random matrix

In [40]:
a1=np.random.random((5,5))

# 5.  How to find common values between two arrays?

In [39]:
a1=np.array([[1,2,3,4]])
a2=np.array([[1,2,4,3,5,6]])
np.intersect1d(a1,a2)

array([1, 2, 3, 4])

# 6.How to get the dates of yesterday, today and tomorrow?

In [46]:
today=np.datetime64('today')
yesterday=today+1
tomorrow=today-1

print("yesterday : ",yesterday)
print("Today : ",today)
print("Tomorrow : ",tomorrow)

yesterday :  2020-07-26
Today :  2020-07-25
Tomorrow :  2020-07-24


# 7. Consider two random array A and B, check if they are equal

In [51]:
A=np.random.random((3,3))
B=np.random.random((3,3))
np.array_equal(A,B)

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [55]:
v1=np.random.random(10)
v1.sort()
v1[-1]

0.9101856579050127

# 9. How to print all the values of an array?

# 10.Subtract the mean of each row of a matrix

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [60]:
a1=np.array([1,2,3,3,3,4,4,5])
z=np.count_nonzero(a1)
z

8

# 14.How to get the n largest values of an array

# 15.How to create a record array from a regular array?